//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTeamNET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectTeamNET.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の対象を選択してください.
        /// </summary>
        public static string ERR_001 {
            get {
                return ResourceManager.GetString("ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出力結果が{0}件を超えています。検索条件を絞り込んでください.
        /// </summary>
        public static string ERR_002 {
            get {
                return ResourceManager.GetString("ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が重複しています.
        /// </summary>
        public static string ERR_003 {
            get {
                return ResourceManager.GetString("ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の内容が正しくありません.
        /// </summary>
        public static string ERR_004 {
            get {
                return ResourceManager.GetString("ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該当データが存在しません.
        /// </summary>
        public static string ERR_005 {
            get {
                return ResourceManager.GetString("ERR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}のため削除できません.
        /// </summary>
        public static string ERR_006 {
            get {
                return ResourceManager.GetString("ERR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを指定してください.
        /// </summary>
        public static string ERR_007 {
            get {
                return ResourceManager.GetString("ERR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルが存在しません.
        /// </summary>
        public static string ERR_008 {
            get {
                return ResourceManager.GetString("ERR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルはCSV形式（拡張子csv）のみ可能です.
        /// </summary>
        public static string ERR_009 {
            get {
                return ResourceManager.GetString("ERR_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザNo、またはパスワードが無効です.
        /// </summary>
        public static string ERR_010 {
            get {
                return ResourceManager.GetString("ERR_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間は当月の日付のみ指定可能です.
        /// </summary>
        public static string ERR_011 {
            get {
                return ResourceManager.GetString("ERR_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間のFromとToの日付が逆転しています.
        /// </summary>
        public static string ERR_012 {
            get {
                return ResourceManager.GetString("ERR_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日別合計を選択した場合、期間は１カ月(３１日)以内としてください.
        /// </summary>
        public static string ERR_013 {
            get {
                return ResourceManager.GetString("ERR_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示項目には所属、ユーザ、テーマ、作業内容、作業内容詳細のいずれか１つを選択してください.
        /// </summary>
        public static string ERR_014 {
            get {
                return ResourceManager.GetString("ERR_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示項目には全体合計、月別合計、日別合計のいずれか１つを選択してください.
        /// </summary>
        public static string ERR_015 {
            get {
                return ResourceManager.GetString("ERR_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}月度の切替は既に実施済です.
        /// </summary>
        public static string ERR_016 {
            get {
                return ResourceManager.GetString("ERR_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーマNOの受注年(4,5桁目)と受付日の年が異なっています.
        /// </summary>
        public static string ERR_017 {
            get {
                return ResourceManager.GetString("ERR_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to １日の工数合計が２４ｈを超えることはできません.
        /// </summary>
        public static string ERR_018 {
            get {
                return ResourceManager.GetString("ERR_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は整数{1}桁まで、小数第{2}位までで入力してください.
        /// </summary>
        public static string ERR_019 {
            get {
                return ResourceManager.GetString("ERR_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}はYYYYMM形式で入力してください.
        /// </summary>
        public static string ERR_020 {
            get {
                return ResourceManager.GetString("ERR_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}月度の工数に未入力日があります。入力をお願いします.
        /// </summary>
        public static string ERR_021 {
            get {
                return ResourceManager.GetString("ERR_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が上限に達したので、登録できませんでした.
        /// </summary>
        public static string ERR_022 {
            get {
                return ResourceManager.GetString("ERR_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内外販区分が正しくありません.
        /// </summary>
        public static string ERR_023 {
            get {
                return ResourceManager.GetString("ERR_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が必要です.
        /// </summary>
        public static string ERR_024 {
            get {
                return ResourceManager.GetString("ERR_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループユーザーは空にすることはできません.
        /// </summary>
        public static string ERR_025 {
            get {
                return ResourceManager.GetString("ERR_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前の保存が必要で、&lt;= 40文字.
        /// </summary>
        public static string ERR_026 {
            get {
                return ResourceManager.GetString("ERR_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}が正常終了しました.
        /// </summary>
        public static string INF_001 {
            get {
                return ResourceManager.GetString("INF_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}します。よろしいですか？.
        /// </summary>
        public static string WAR_001 {
            get {
                return ResourceManager.GetString("WAR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力内容が更新されていませんが画面を切替えてよろしいですか？.
        /// </summary>
        public static string WAR_002 {
            get {
                return ResourceManager.GetString("WAR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計工数が８ｈ末満です.
        /// </summary>
        public static string WAR_003 {
            get {
                return ResourceManager.GetString("WAR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工数が未入力です.
        /// </summary>
        public static string WAR_004 {
            get {
                return ResourceManager.GetString("WAR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 売上済のテーマです。テーマを追加しますか？.
        /// </summary>
        public static string WAR_005 {
            get {
                return ResourceManager.GetString("WAR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の月度切替をします。 当月データは前月分として繰越され、元に戻せなくなります。よろしいですか？.
        /// </summary>
        public static string WAR_006 {
            get {
                return ResourceManager.GetString("WAR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存前ですが処理を続行しますか？.
        /// </summary>
        public static string WAR_007 {
            get {
                return ResourceManager.GetString("WAR_007", resourceCulture);
            }
        }
    }
}
